import { Injectable, BadRequestException } from '@nestjs/common';
import { AdvisoryRequestDto } from './dto/advisory-request.dto';
import {
  AgroAdvisory,
  AdvisorySeverity,
  UncertaintyEvaluation,
} from './interfaces/advisory.interface';
import {
  classifyRainfall,
  RAINFALL_RULES,
  getCategoriesSpanned,
  formatCategorySpanNote,
  getAncillaryNotices,
} from './rules/rainfall.rules';

@Injectable()
export class AdvisoriesService {
  /**
   * Deterministically evaluates the meteorological inputs and generates rule-based agro-advisories.
   */
  generateAdvisory(dto: AdvisoryRequestDto): AgroAdvisory {
    // 1. Validate interval consistency if provided
    if (
      dto.lower_80_mm !== undefined &&
      dto.upper_80_mm !== undefined &&
      dto.lower_80_mm > dto.upper_80_mm
    ) {
      throw new BadRequestException(
        `Invalid 80% conformal interval: lower_80_mm (${dto.lower_80_mm}) cannot exceed upper_80_mm (${dto.upper_80_mm}).`,
      );
    }

    if (
      dto.lower_90_mm !== undefined &&
      dto.upper_90_mm !== undefined &&
      dto.lower_90_mm > dto.upper_90_mm
    ) {
      throw new BadRequestException(
        `Invalid 90% conformal interval: lower_90_mm (${dto.lower_90_mm}) cannot exceed upper_90_mm (${dto.upper_90_mm}).`,
      );
    }

    // 2. Classify downscaled point rainfall
    const rainfallMm = Number(dto.rainfall_mm.toFixed(2));
    const category = classifyRainfall(rainfallMm);
    const rule = RAINFALL_RULES[category];

    let severity = rule.severity;
    const recommendations = [...rule.recommendations];

    // 3. Evaluate conformal uncertainty intervals
    let uncertainty: UncertaintyEvaluation | undefined;
    const basis: string[] = [
      `ML downscaled precipitation prediction (XGBoost ${dto.model_version || 'v0.1.0-alpha'})`,
      'Deterministic rule engine thresholds',
    ];

    if (dto.lower_80_mm !== undefined && dto.upper_80_mm !== undefined) {
      const lower = Number(dto.lower_80_mm.toFixed(2));
      const upper = Number(dto.upper_80_mm.toFixed(2));
      const width = Number((upper - lower).toFixed(2));
      const categoriesSpanned = getCategoriesSpanned(lower, upper);
      const spansMultiple = categoriesSpanned.length > 1;

      let note = spansMultiple ? formatCategorySpanNote(categoriesSpanned) : undefined;

      // Severity escalation: If point estimate is INFO (very low or light), but upper bound >= 5.0 mm
      if (severity === AdvisorySeverity.INFO && upper >= 5.0) {
        severity = AdvisorySeverity.WATCH;
        note = note
          ? `${note} (Severity elevated to WATCH due to calibrated upper bound extending into higher rainfall regimes.)`
          : 'Severity elevated to WATCH due to calibrated upper bound extending into higher rainfall regimes.';
      }

      uncertainty = {
        level: '80%',
        lower_mm: lower,
        upper_mm: upper,
        interval_width_mm: width,
        spans_multiple_categories: spansMultiple,
        categories_spanned: categoriesSpanned,
        uncertainty_note: note,
      };

      basis.splice(1, 0, 'Split-conformal prediction intervals calibrated on Baramati validation partition');
    }

    // 4. Ancillary meteorological conditions
    const ancillaryNotices = getAncillaryNotices({
      temperature_max: dto.temperature_max,
      humidity: dto.humidity,
      wind_speed: dto.wind_speed,
    });

    // 5. Build structured response with provenance and scientific disclaimer
    return {
      panchayat_id: dto.panchayat_id,
      panchayat_name: dto.panchayat_name,
      date: dto.date,
      rainfall_mm: rainfallMm,
      rainfall_category: category,
      category_label: rule.label,
      severity,
      headline: rule.headline,
      recommendations,
      ancillary_notices: ancillaryNotices,
      uncertainty,
      basis,
      data_context: {
        historical_experiment: true,
        experiment_date: dto.date,
        reference_proxy: 'ERA5-Land (0.1°)',
        input_proxy: 'NASA POWER / MERRA-2 (0.5°)',
        model_version: dto.model_version || 'v0.1.0-alpha',
        disclaimer:
          'This advisory is generated by a deterministic prototype rule engine based on a retrospective downscaling experiment. It does not replace official IMD/agricultural department forecasts or expert agronomist recommendations.',
      },
    };
  }
}
