import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { RainfallCategory, AdvisorySeverity } from '../interfaces/advisory.interface';

export class UncertaintyEvaluationDto {
  @ApiProperty({ description: 'Conformal coverage confidence level', example: '80%' })
  level: string;

  @ApiProperty({ description: 'Calibrated lower bound (mm)', example: 0.4 })
  lower_mm: number;

  @ApiProperty({ description: 'Calibrated upper bound (mm)', example: 16.73 })
  upper_mm: number;

  @ApiProperty({ description: 'Prediction interval width (mm)', example: 16.33 })
  interval_width_mm: number;

  @ApiProperty({ description: 'Whether the prediction interval spans multiple rainfall categories', example: true })
  spans_multiple_categories: boolean;

  @ApiProperty({ description: 'Rainfall categories spanned by the interval', example: ['very_low', 'light', 'moderate'] })
  categories_spanned: RainfallCategory[];

  @ApiPropertyOptional({
    description: 'Human-readable explanation of uncertainty span across categories',
    example: 'Rainfall category has uncertainty: the calibrated interval spans very low through moderate rainfall.',
  })
  uncertainty_note?: string;
}

export class AdvisoryDataContextDto {
  @ApiProperty({ description: 'Confirms output is a retrospective historical experiment', example: true })
  historical_experiment: boolean;

  @ApiProperty({ description: 'Experiment observation date (YYYY-MM-DD)', example: '2024-09-01' })
  experiment_date: string;

  @ApiProperty({ description: 'Reference proxy source (not ground truth)', example: 'ERA5-Land (0.1°)' })
  reference_proxy: string;

  @ApiProperty({ description: 'Coarse weather input proxy', example: 'NASA POWER / MERRA-2 (0.5°)' })
  input_proxy: string;

  @ApiProperty({ description: 'Active ML downscaler version', example: 'v0.1.0-alpha' })
  model_version: string;

  @ApiProperty({
    description: 'Scientific and operational boundary disclaimer',
    example:
      'This advisory is generated by a deterministic prototype rule engine based on a retrospective downscaling experiment. It does not replace official IMD/agricultural department forecasts or expert agronomist recommendations.',
  })
  disclaimer: string;
}

export class AdvisoryResponseDto {
  @ApiProperty({ description: 'Gram Panchayat identifier', example: 'P01' })
  panchayat_id: string;

  @ApiPropertyOptional({ description: 'Gram Panchayat name', example: 'Baburdi' })
  panchayat_name?: string;

  @ApiProperty({ description: 'Experiment date', example: '2024-09-01' })
  date: string;

  @ApiProperty({ description: 'Downscaled precipitation prediction (mm)', example: 8.56 })
  rainfall_mm: number;

  @ApiProperty({ enum: RainfallCategory, example: RainfallCategory.MODERATE })
  rainfall_category: RainfallCategory;

  @ApiProperty({ description: 'Human-readable category label', example: 'MODERATE RAINFALL' })
  category_label: string;

  @ApiProperty({ enum: AdvisorySeverity, example: AdvisorySeverity.WATCH })
  severity: AdvisorySeverity;

  @ApiProperty({ description: 'Short advisory headline', example: 'Moderate rainfall signal' })
  headline: string;

  @ApiProperty({
    description: 'Deterministic agricultural advisory bullet points',
    example: [
      'Moderate rainfall (5–20 mm) is indicated for the Panchayat.',
      'Consider postponing sensitive field operations (e.g. spraying, weeding, harvesting) that depend on dry foliage or soil.',
      'Monitor plot drainage channels and standing water in lower plot sections.',
    ],
  })
  recommendations: string[];

  @ApiProperty({
    description: 'Ancillary meteorological observations (e.g. temperature, wind, humidity)',
    example: [
      'High relative humidity is indicated. Local crop and field conditions should be monitored, particularly where prolonged moisture is present.',
    ],
  })
  ancillary_notices: string[];

  @ApiPropertyOptional({ type: UncertaintyEvaluationDto })
  uncertainty?: UncertaintyEvaluationDto;

  @ApiProperty({
    description: 'Analytical basis and provenance for the generated advisory',
    example: [
      'ML downscaled precipitation prediction (XGBoost v0.1.0-alpha)',
      'Split-conformal prediction intervals calibrated on Baramati validation partition',
      'Deterministic rule engine thresholds',
    ],
  })
  basis: string[];

  @ApiProperty({ type: AdvisoryDataContextDto })
  data_context: AdvisoryDataContextDto;
}
